Changed strategy to determine directory of python script
Now it reads it from the same path as the wrapper script

Signed-off-by: Claudio Matsuoka <cmatsuoka@gmail.com>

diff --git a/codecgraph b/codecgraph
--- a/codecgraph
+++ b/codecgraph
@@ -2,6 +2,7 @@
 
 version="1.0"
 name=`basename $0`
+dir=`dirname $0`
 fmt="svg"
 usage="Usage: $name [-f format] [-h] [-o name] [-v] [codecfile]"
 help="Options:
@@ -52,8 +53,8 @@ if [ -z "$codecfile" ]; then
     exit 1
 fi
 
-if [ -z "`which codecgraph.py`" ]; then
-    echo "error: can't find codecgraph.py in PATH (package corrupt?)" >&2
+if [ ! -x $dir/codecgraph.py ]; then
+    echo "error: can't execute codecgraph.py (package corrupt?)" >&2
     exit 1
 fi
 
@@ -78,7 +79,7 @@ if [ $? -ne 0 ]; then
 fi
 
 dotfile=`mktemp -t codecgraph.XXXXXX`
-codecgraph.py $codecfile > $dotfile
+$dir/codecgraph.py $codecfile > $dotfile
 echo Generating $outfile.$fmt
 dot -T$fmt -o$outfile.$fmt $dotfile
 rm $dotfile
